# ruff.toml â€” compatible with Ruff >=0.14
line-length = 88
target-version = "py310"
builtins = ["_"]
exclude = [".venv", "build", "dist", "__pycache__", ".ruff_cache"]
extend-exclude = ["tests", "src/bad.py"]
fix = true
fix-only = false
force-exclude = true
respect-gitignore = true
output-format = "grouped"
unsafe-fixes = true

[format]
docstring-code-format = true
docstring-code-line-length = 60
indent-style = "space"
indent-width = 4

[analyze]
detect-string-imports = true
direction = "dependencies"
exclude = ["generated"]
preview = true
string-imports-min-dots = 2
type-checking-imports = true
include-dependencies = { "foo/bar.py" = ["foo/baz/*.py"] }
